version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - "8083:80"

  backend:
    image: backend
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dockerDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: me

  db:
    image: postgres
    environment:
      POSTGRES_DB: dockerDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: me
    ports:
      - "5433:5432"
